### ISSUE TITLE
Python Roadmap Your Path to Python Master

### ISSUE THREAD

**Issue by orioninsist** [orioninsist/orioninsist.github.io#57]
1. [ ] Medium Publish
2. [ ] Link Description Content with Emoji and tags Create on /media
3. [ ] Linkedin Publish Company and Personal Account
4. [ ] Patreon Publish
5. [ ] Ko-fi Publish
6. [ ] Buymecoffee Publish
7. [ ] Twitter Publish
8. [ ] Facebook Publish
9. [ ] Instagram Publish
10. [ ] Pinterest Publish
